### ISSUE TITLE
Tags associated with notes absent from report

### ISSUE THREAD

**Issue by earcanal** [retorquere/zotero-report-customizer#14]
With Tags and Notes ticked, my report shows tags for the _item_, but not the notes.

If you happen to touch this, can I also add a feature request to report notes in a table with options to ORDER and GROUP BY tag (sorting/grouping using other note metadata would be a bonus ;-)

**Comment by retorquere** [comment]
I'll look into the notes tag. Could you please file a separate issue for the order/group by enhancement?
