### ISSUE TITLE
No checkboxes are ticked (Javascript error)

### ISSUE THREAD

**Issue by melat0nin** [retorquere/zotero-report-customizer#18]
I've just noticed that none of the checkboxes in the Report Customizer are checked, although in about:config they can be manually edited (changing the checkboxes makes no difference). Also, the Report Sort Order tab just has one entry - "Field".

I've tried reinstalling the XPI (0.2.19) and I'm running Standalone v 4.0.28.7.

Just noticed this line in the debug output;

`[JavaScript Error: "InvalidCharacterError: String contains an invalid character" {file: "chrome://zotero-report-customizer/content/zotero-report-customizer.js" line: 196}]`

From what I can see from the source XPI this is the relevant section:

    XmlNode.prototype.set = function() {
    var attr, attrs, i, len, name, node, value;
    node = arguments[0], attrs = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    for (i = 0, len = attrs.length; i < len; i++) {
      attr = attrs[i];
      for (name in attr) {
        if (!hasProp.call(attr, name)) continue;
        value = attr[name];
        switch (false) {
          case typeof value !== 'function':
            value.call(new this.Node(this.namespace, node, this.doc));
            break;
          case name !== '':
            node.appendChild(this.doc.createTextNode('' + value));
            break;
          default:
            node.setAttribute(name, '' + value);
        }
      }
    }
    };

Line 196 is the `switch` statement's default case:

`node.setAttribute(name, '' + value);`

Without looking into it further I'm assuming there's something not being properly escaped in one (or more) attributes' names.

**Comment by k-go** [comment]
I am having the same issue described above with latest versions of both the plugin and Zotero. Reports are generated with all fields, no matter what I select. I am new to Zotero. I will try using an older version of the plugin and report whether that works.

**Comment by retorquere** [comment]
Can you get me a copy of the debug log?

**Comment by jsmith767** [comment]
I'm having the same problem as mentioned above as well.

**Comment by k-go** [comment]
Sorry I never got a chance to find the debug log - I will first need to figure out how to get it! But I did try installing the previous version of the plugin and that worked, so I hope that is helpful for jsmith767 at least.

**Comment by retorquere** [comment]
you can get the debug log by typing `zotero://debug` in the address field.

**Comment by BenjaminHCCarr** [comment]
I am using Zotero Standalone 4.0.29.5 on Win 7.
I am using the latest version:
https://github.com/ZotPlus/zotero-report-customizer/releases/download/0.2.19/zotero-report-customizer-0.2.19.xpi
I have attached the "on load" error.

Looks to be line 196:
[JavaScript Error: "InvalidCharacterError: String contains an invalid character" {file: "chrome://zotero-report-customizer/content/zotero-report-customizer.js" line: 196}]

[zot_rep_debug_on_load.txt](https://github.com/ZotPlus/zotero-report-customizer/files/180556/zot_rep_debug_on_load.txt)

**Comment by retorquere** [comment]
No idea what it's passing weird property names, but could you try [this version](http://tempsend.com/049E790709) with Zotero debug logging on? If it happens again, the name will be in the logs.

**Comment by BenjaminHCCarr** [comment]
That works, at least on my Mac, same Zotero Standalone Version though, but the check-boxes were pre-checked and the Sort box had options. The report output was as specified! Thanks for the GREAT and QUICK fix!

Just two things:

1) Extra appears twice in every “Field”, it’s correctly in order and then tacked on again as the last item in every item type.

2) Here is the debug log, I assume the ~2900 logged lines are how many attributes there are?
—————————————————————————————————
version => 4.0.29.5, platform => MacIntel, oscpu => Intel Mac OS X 10.10, locale => en-US, appName => Zotero, appVersion => 4.0.29.5

=========================================================

(3)(+0000000): Adding attribute: "container"

(3)(+0000000): Adding attribute: "properties"

(3)(+0000000): Adding attribute: "editable"

(3)(+0000000): Adding attribute: "editable"

(3)(+0000000): Adding attribute: "label"

(3)(+0000001): Adding attribute: "class"

>2900 lines?

**Comment by retorquere** [comment]
Argh, that wasn't a fix, I just added logging. I hate these transient
errors.

**Comment by BenjaminHCCarr** [comment]
Well I'll elaborate on what was going on with the PC. It's a win7 whatever from the log output.
No checkboxes were checked on load, and there were no options listed in the Sort window. 

It also gave that:
[JavaScript Error: "InvalidCharacterError: String contains an invalid character" {file: "chrome://zotero-report-customizer/content/zotero-report-customizer.js" line: 196}]
error.

On My MAC 10.10 with the same version of Zotero Standalone and the exact same library (I use WebDav sync),  the report is generated correctly with the debug plugin you linked. With the debug plugin, the checkboxes were pre-checked and I had a populated and editable Sort window.

Give me five minutes, I'll grab stable and see if it happens on the Mac. I am wondering if it is a PC/Windows/Unicode error and not you!

**Comment by BenjaminHCCarr** [comment]
Fails in the same way with stable on Mac. Screenshots and debug attached.
![screen shot 2016-03-19 at 2 28 28 pm](https://cloud.githubusercontent.com/assets/8225968/13900540/195dea30-eddf-11e5-9895-2bb36d56e361.png)
![screen shot 2016-03-19 at 2 28 33 pm](https://cloud.githubusercontent.com/assets/8225968/13900541/195e5c40-eddf-11e5-89ab-6fe6cca7a757.png)
[debug_zotero-report-customizer-0.2.19.txt](https://github.com/ZotPlus/zotero-report-customizer/files/180954/debug_zotero-report-customizer-0.2.19.txt)

**Comment by retorquere** [comment]
Unfortunately, without the debug logging, I can't tell what attribute is triggering this, as there is no trace with the error. I'll have to figure this out from just going through the code for potential errors, but I've added just a single line to output the attribute name to the log before adding it.... and somehow, that works.

**Comment by BenjaminHCCarr** [comment]
Bah, how frustrating for you!

OKAY! So this is weird. I just switched back to the debug XPI, and got errors (I had no previous installation of customizer on home machine). Attaching log, bit it looks to be the last 4 lines:
----------------------------
(5)(+0000118): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE sourceItemID=? AND linkMode NOT IN (?) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY mimeType='application/pdf' DESC, value=? DESC, dateAdded ASC

(5)(+0000000): Binding parameter 1 of type int: 1246

(5)(+0000001): Binding parameter 2 of type int: 3

(5)(+0000000): Binding parameter 3 of type string: ""
[debug_zoteroreportcustomizer0.2.1739631458405494.txt](https://github.com/ZotPlus/zotero-report-customizer/files/180966/debug_zoteroreportcustomizer0.2.1739631458405494.txt)

**Comment by BenjaminHCCarr** [comment]
happy to work with you, I am working on dissertation today and don't need to make any reports but will have Zotero open, etc.

I also love and use a ton of your stuff so happy to help if I can. Attaching "working" screenshots.
![screen shot 2016-03-19 at 2 55 03 pm](https://cloud.githubusercontent.com/assets/8225968/13900690/99bbcda2-ede2-11e5-8007-9e225bd2fedf.png)
![screen shot 2016-03-19 at 2 54 58 pm](https://cloud.githubusercontent.com/assets/8225968/13900691/99d76ada-ede2-11e5-8dbf-ca68efdea933.png)

**Comment by retorquere** [comment]
I appreciate your patience. Unfortunately, the screenshots don't give me the information I need, and the last log doesn't have any errors (it does happily report a ton of valid attributes being added).

That last query is not mine, it's from Zotero proper.

**Comment by BenjaminHCCarr** [comment]
Yeah, I was just trying to show you what we were saying in words about the unpopulated checkboxes and no sort options. I know screenshots, unless it's of the errors don't generally help a lot.

Okay, not sure this will help a ton, but it wasn't all constantly the same lines, even though it looked like it was.

I just took the debug log, sorted, and uniq'ed it (attached) very un-scientifically.....
There is a:

(3)(+0000001): Adding attribute: "allowevents"
but no +0000000 like the other attiributes?

There are three "containers"
(3)(+0000000): Adding attribute: "container"
(3)(+0000001): Adding attribute: "container"
(3)(+0034239): Adding attribute: "container"

There is one: (3)(+0000000): Adding attribute: "ondragover" and "ondrop" but no +1 for these?

Any help? 5852 lines is a lot to sort through.
-Ben
[debug_zotero_sort_uniq.txt](https://github.com/ZotPlus/zotero-report-customizer/files/180985/debug_zotero_sort_uniq.txt)

**Comment by retorquere** [comment]
It's actually just the last instance I need when the error occurs. All the rest can be ignored. The number in front is just the elapsed time since the previous log message.

**Comment by BenjaminHCCarr** [comment]
This sadly isn't at all helpful, but I am attaching the debug log from the debug XPI on Win7. It's the same as on Mac, it works, and it's just all the attributes. Happy to try anything you can come up with though.
-Ben
[zot_rep_debug_on_load_win7.txt](https://github.com/ZotPlus/zotero-report-customizer/files/182352/zot_rep_debug_on_load_win7.txt)

**Comment by BenjaminHCCarr** [comment]
Here is the log for 0.2.2.1 on Win7, no checkboxes checked, and sort field empty.
[zot_rep_0.2.2.1_debug_on_load_win7.txt](https://github.com/ZotPlus/zotero-report-customizer/files/182493/zot_rep_0.2.2.1_debug_on_load_win7.txt)

**Comment by retorquere** [comment]
If adding the debug logging makes it work, perhaps simply rebuilding & republishing will do the trick. Could you try grabbing 0.2.26?

**Comment by BenjaminHCCarr** [comment]
Thanks. 0.2.26, works like the debug version. Off problem, but if debug logging makes it work, it makes it work, happy to close this til we run into another block. Thanks for your help.I wonder what the root problem is, but a functional plugin is preferable to trying to track down a stray '/:/:/" in thousands of lines.

Thanks for your help the new release works well.

**Comment by BenjaminHCCarr** [comment]
Oh sorry it it took so long, PhD work, Work work, and Sick baby,

**Comment by retorquere** [comment]
Crap, either on of those could do you in. Hang in there.

**Comment by BenjaminHCCarr** [comment]
retorquere, doh, I just assumed the 0.0.26 was the test build.

Happy to keep messing it, I have multiple platforms, but the 0.0.26 build works on Stand alone on Mac OSX.

**Comment by retorquere** [comment]
I have no idea why, but if it does, profit.

**Comment by BenjaminHCCarr** [comment]
Seeing as you are charging $0 / $0 Euro......

ANd happy to work with crazy academics like me......

Do you have a paypal. etc, where I can send you a six pack of the beer of your choice.

Having written OOS, supported OSS, I use your plugin, I would be happy to buy you a 6-pack.

**Comment by retorquere** [comment]
I don't think Paypal sends beers 😄 . 

I hugely appreciate your  positive feedback. That in itself is already plenty reward. *but!* [This](https://www.linkedin.com/in/bencarr) is you, right? I drink only very occasionally, but you could make me Worlds Best Dad For A Week by sending a postcard or whatnot with a dolphin if you have it to

Alexandra Heyns
Deurnestraat 127
6843PP Netherlands

I have an 8 year old daughter who is adamant she's going to be a dolphin trainer; I'm sort of hoping that is just 8-year-oldish for "I want to work with dolphins" which could sensibly translate to "marine biologist".

Thanks!

```







































```

Oh, you're still here? Well, you could look through my [wishlist](http://zotplus.github.io/wishlist.html), but I want to impress upon you that the hugs I'm going to get over that postcard are going to be ample reward.

**Comment by retorquere** [comment]
(BTW working with academics is what keeps me sane in this world, so any possible debt goes the other way)
