### ISSUE TITLE
Authors one line

### ISSUE THREAD

**Issue by cass00** [retorquere/zotero-report-customizer#20]
Could there be an option to only have one "Author" entry with all authors listed instead of having one line with "Author" for each author.

**Comment by retorquere** [comment]
Can you try this one: http://ge.tt/5lPnqRd2

**Comment by cass00** [comment]
Works nicely. Would be possible to make this optional via some check button?

**Comment by retorquere** [comment]
There isn't a checkbox for it but I've added a [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) named `extensions.zotero.report-customizer.join-authors`; if you make a new string key in the hidden preference by that name, and you enter there the separator you want to use (such as " and "), the report customizer will join the names using that in the report. Note that this will ignore the creator type, and the entire set of authors will be listed as whatever creator type (author, editor, whatever) as the first one.
