### ISSUE TITLE
"Web Page" Missing from Type

### ISSUE THREAD

**Issue by keladeine** [retorquere/zotero-report-customizer#21]
There's every type of citation except 'web page' in the list of types under "fields to show in report"
<img width="186" alt="missing" src="https://cloud.githubusercontent.com/assets/22404548/18948043/887f5496-8603-11e6-8680-8f90d696827f.png">
<img width="940" alt="zotero" src="https://cloud.githubusercontent.com/assets/22404548/18948044/8880a1a2-8603-11e6-928a-99e5066b3f58.png">

**Comment by keladeine** [comment]
is there a plan to add it? I appreciate all you do. I just need to plan for my own organization. "web page" is my most common type.

**Comment by retorquere** [comment]
I don't add them manually, I request them from Zotero, but it looks my request was incomplete. Can you try https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-0.2.26-circle-6.xpi ?
