### ISSUE TITLE
A plea for a more concise report to serve people who use notes =)

### ISSUE THREAD

**Issue by Verkiel** [retorquere/zotero-report-customizer#30]
In response to the [discussion](https://forums.zotero.org/discussion/comment/333333#Comment_333333) on the zotero forum:
The problem with the current report is that a lot of space is dedicated to item details that can't be made smaller. E.g. the author list is one column, and you can either have them all, or none, as is. 
I make use of notes a lot, and what I need is something that concisely tells me what article it's about, like a common bibliography item, and then my tags and notes and perhaps some other stuff that doesn't generally occur in a reference. I mainly have journal articles and book chapters, so that's rather straightforward. 

I am thinking something like attached [Zotero custom report wish.pdf](https://github.com/retorquere/zotero-report-customizer/files/3254291/Zotero.custom.report.wish.pdf), would have specifications as followed:
A Zotero report that displays a citation-like identification of items, followed by Zotero specific data of that item, including tags and notes, **ordered by first author’s last name**.
### Item details:
Each item starts on a new page.
The header is the _item type_.
In “body” text followed by a citation-like representation of the item.
The point of it being that it is concise and doesn’t take a lot of space on the page. Also, if it is a header, when polishing it up in a text editor, it's easy to index.

Followed by a section in “h1” text called “Details” with details that are absent from the citation, such as:
•	Abstract
•	URL
•	Extra
•	Date added
•	Etc.
Preferably selectable, and all details, where available, preceded by a “h2” header.

Followed by a section “Tags” in “h1” style, that contains tags, _ordered alphabetically_, in 4 columns. Tags should include correct emojis (May 2019, so not like the example, but the zotero report does it fine already), and don't snicker at emojis, I am lysdectic, they help a bunch!

Then a section called “Notes” in “h1”.
Followed by the notes, _in alphabetical order_, indented and separated. If there is a way to shift the header styles in the notes with one position, that would be very helpful. They are of course in html and can have header styles that will start with h1, which should be h2, etc.

Ending with a list of the other attachments, without further notes or tags of those attachments.

Or something of the sort. Gosh that would be so tremendously helpful!

PS. for reference, the current report of that same item looks like this 
[Zotero Report current.pdf](https://github.com/retorquere/zotero-report-customizer/files/3254326/Zotero.Report.current.pdf) (and yes, I'd have to change the first line of my notes to get them in the order I want, but I don't see how that could be solved more efficiently)

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.20.113](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.20.113.xpi) ("add bibliography option to RC")

Install in Zotero by downloading [test build 5.0.20.113](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.20.113.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Let's take it one thing at a time. If you install build 113 linked to above, you can find a [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) called `extensions.zotero.report-customizer.bibliography`. If you toggle that to `true`, the title in the report will be replaced with a bibliography rendering according to the default quick-copy format (Prefs - Export - Default Format). If you click the pencil in the report, you can remove and reorder fields.

**Comment by Verkiel** [comment]
SO MUCH BETTER ALREADY!!!!!!!!!! 
Man, I can't tell you how helpful this is... still the issue with the weird sorts of almost everything. But wow. Yes!

**Comment by retorquere** [comment]
Weird sorts?

**Comment by Verkiel** [comment]
Yeah, I mean, whom ever would want articles sorted by their title? 
No idea how the tags are sorted, but it's not alphabetically. 
The attachment are sorted by date added, I think, and considering that is not something you can change, that doesn't seem the most rational thing to sort them by, etc...

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.20.114](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.20.114.xpi) ("sort tags")

Install in Zotero by downloading [test build 5.0.20.114](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.20.114.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.20.115](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.20.115.xpi) ("sort attachments")

Install in Zotero by downloading [test build 5.0.20.115](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.20.115.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
> Yeah, I mean, whom ever would want articles sorted by their title?

Presumably whomever put together the standard Zotero report 🤷‍♂ . The customizer only allows re-sorting and field removal of the existing Zotero report. I think the sort can be affected in Zotero, but I don't know how -- I just use the RC to re-sort.

> No idea how the tags are sorted, but it's not alphabetically.
> The attachment are sorted by date added, I think, and considering that is not something you can change, that doesn't seem the most rational thing to sort them by, etc...

Both are sorted alphabetically now in 115.

**Comment by Verkiel** [comment]
You are amazing!!!!!

**Comment by retorquere** [comment]
Opinions on that matter vary (or at least, I see wildly different interpretations of that term), but I'll take it.

Are you Dutch by any chance?

**Comment by Verkiel** [comment]
Totally and utterly :D

**Comment by retorquere** [comment]
In dta geval: hoi daar. Als de veranderingen zo naar wens zijn dan kan ik een nieuwe release de deur uit doen.

**Comment by Verkiel** [comment]
Het is een Enorme Verbetering, dank je wel!!!

**Comment by Verkiel** [comment]
Oh, ik zie een probleempje: ik krijg nog maar een notitie per item in de laatste versie.

**Comment by retorquere** [comment]
(switching back to English for potential other readers) only one note is being displayed?

**Comment by Verkiel** [comment]
Yes, indeed

**Comment by retorquere** [comment]
I can't reproduce this. When I multiple notes on an item, all are displayed. Are you exporting selected items, or a collection?

**Comment by Verkiel** [comment]
Apologies for ridiculously tardy reply!
It was a user error, which actually delighted me when I figured it out: I did a report based on search results where I searched for attachments with a certain tag - which I only apply to one type of notes - and this is the way to actually get just one type of note in your report. This is totally groovy :D 

In other news, now that Zotero updated to 5.0.68, the report no longer displays tags. Do I maybe need to reinstall something?
Related: while editing the report, if you remove the section of tags that go with a note, the tags that go with the main item also disappear. I can't reproduce that at the moment, because I'm not getting tags at all.

**Comment by retorquere** [comment]
I'd have to look into why it doesn't work on latest zotero, but that will have to wait until Sunday.

The editing in the RC doesn't actually remove anything from items, it removes a category of things to display, so yes, if you remove tags anywhere, you remove them everywhere.

**Comment by Verkiel** [comment]
Thanks for looking into it!

**Comment by retorquere** [comment]
On 5.0.68, it displays tags as normal for me. Are you sure you didn't remove tags while editing the report? You can reset all edits using the reset icon (a circular arrow).
