### ISSUE TITLE
New version not found via Zotero "check for updates" menu entry

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-report-customizer#32]
I noticed that Zotero was unable to find the last 2 versions of zotero-report-customizer when I clicked the "check for updates" menu entry from the Add-ons manager.

I'm using Zotero 5.0.71.

**Comment by retorquere** [comment]
Thanks for reporting this. I've fixed it, but unfortunately the fix will only go into effect for people already on the new v5.0.24 -- after manual upgrade, the rest should be automatic.

**Comment by ngirard** [comment]
Great, thanks!

**Comment by retorquere** [comment]
You can't win from label-gun :smile:
