### ISSUE TITLE
Z5: how to use

### ISSUE THREAD

**Issue by esquires** [retorquere/zotero-report-customizer#33]
I apologize for the simple question, but it wasn't clear how to use the functionality from this extension. I have it installed but I am not sure how to customize the reports. Are there buttons that are supposed to show up somewhere? Thanks.

I am specifically trying to understand the live-edit comment from the README:
```
Does what Jason Priem's "Report Cleaner", but without the copy-paste-into-website bit. You can live-edit the report to pick the elements to remove from the report, and they will simple not show up from that point on.
```

**Comment by retorquere** [comment]
If you generate a report, there should be a pencil icon at the top. If you click that, you can edit your reports.

You'll need to upgrade to 5.0.25 of the plugin because saving was broken in Zotero 5.0.71.

**Comment by esquires** [comment]
Thanks. I see it now.
