### ISSUE TITLE
Feature suggestion: separate CSS

### ISSUE THREAD

**Issue by Verkiel** [retorquere/zotero-report-customizer#34]
Alternatively: an option to start every item on a new page =)
With the CSS baked into the report, there's no way to customise this. I'd rather not have to delve into it, but it might be the easier option to realise.
And then it's probably also easier to do something about the font sizes of headers and stuff, so that would be better. 
Thanks!

**Comment by retorquere** [comment]
Separating the CSS is not going to happen, but injecting overriding CSS is possible. As the injected CSS comes after the bundled CSS, it should override everything there. Alternately, I can just not inject the bundled CSS at all, but you'd need to replicate all parts of it you still want rather than just overriding it.

**Comment by Verkiel** [comment]
Thanks for the superfast response :). You lost me after "Alternatively", so my preference is whatever you suggested first. I'm virtually unacquainted with CSS: all I want is items to start on a new page, but whatever is necessary to make that happen sooner rather than later, I'm in.

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.25.126](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.126.xpi) ("fixes #34")

Install in Zotero by downloading [test build 5.0.25.126](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.126.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
If you install .126 from above, open the Zotero [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences) and create the string key `extensions.zotero.report-customizer.css`, you can add any CSS you want to have show up in the report in that string.

**Comment by Verkiel** [comment]
Groovy :D thanks! Now all I need to do is figure out how to make a CSS file... surely this won't take an awful lot of time :))
Would it be a lot of trouble to point me to the CSS as it is used in the current report customizer report? Then at least I know where to start. Much obliged!

**Comment by retorquere** [comment]
The CSS is massive as I'm importing Materialize CSS, you don't really want to look at that. The individual items are wrapped in `li.item`, so something like this might already work:

```
li.item { page-break-after: always; }
```

but I'm honestly no expert at CSS.

If you find something that works for you I can merge the new custom css feature and cut a new release.

**Comment by Verkiel** [comment]
Thanks for that! I will fiddle with it later, and get back if I have something interesting to say about it :D

**Comment by retorquere** [comment]
Any updates?

**Comment by dchawisher** [comment]
@retorquere I cannot install the old report-customizer build because I am using Juris-M, but I would benefit from the custom css feature if it is still possible to include it.
