### ISSUE TITLE
Select Item link in list of available report fields

### ISSUE THREAD

**Issue by hp6393** [retorquere/zotero-report-customizer#35]
Would it be possible to add the Select Item link as an option to the fields in a report? Adam Smith posted Javascript code for this awhile ago:

```
function doExport() {
	var item;
	while(item = Zotero.nextItem()) {
		Zotero.write("zotero://select/items/");
		var library_id = item.libraryID ? item.libraryID : 0;
		Zotero.write(library_id+"_"+item.key);
	}
}
```

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.25.128](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.128.xpi) ("add select link")

Install in Zotero by downloading [test build 5.0.25.128](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.128.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give the version linked above a try

**Comment by hp6393** [comment]
Thanks for the quick response. This works fine for reports of parent items--a real help that lets me link back to Zotero from other applications. However, when I generate a report on a child note the Select Item is not shown with the parent title (see example attachments). Also, if I generate a report for a standalone note, it does not list the Select Item. (Both child and standalone notes have their own Select Item link that is different from the parent Select Item.) Is there any way to add Select Item to these as well?

![Parent with all child entries](https://user-images.githubusercontent.com/55008228/64478278-25acbd80-d174-11e9-88be-e76b6afbbb50.jpg)
![Child Note only](https://user-images.githubusercontent.com/55008228/64478279-25acbd80-d174-11e9-911b-a12d9be7b09b.jpg)

**Comment by retorquere** [comment]
I saw a notification of a reply of yours, but I don't see the reply here. What did it say?

**Comment by hp6393** [comment]
It works great for parent items, exactly what I needed to be able to link with other apps. However, it does not include the select item for child or stand alone notes, both of which also support select item. Having this for notes is really important because sometimes it is difficult to determine what parent item they are sociated with just from the title. I included a couple of screenshots in my get hub reply. They might help you see what I'm talking about. Again, thanks for considering this.
-------- Original message --------From: Emiliano Heyns <notifications@github.com> Date: 9/7/19  1:14 PM  (GMT-06:00) To: retorquere/zotero-report-customizer <zotero-report-customizer@noreply.github.com> Cc: hp6393 <harold.peach@gmail.com>, Author <author@noreply.github.com> Subject: Re: [retorquere/zotero-report-customizer] Select Item link in list of available report fields (#35) I saw a notification of a reply of yours, but I don't see the reply here. What did it say?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/retorquere/zotero-report-customizer/issues/35?email_source=notifications\u0026email_token=ANDVXZFUVCGUGT7XFHCRPJ3QIPVPXA5CNFSM4IUOMPXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6E63DQ#issuecomment-529132942",
"url": "https://github.com/retorquere/zotero-report-customizer/issues/35?email_source=notifications\u0026email_token=ANDVXZFUVCGUGT7XFHCRPJ3QIPVPXA5CNFSM4IUOMPXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6E63DQ#issuecomment-529132942",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by retorquere** [comment]
I don't see those screenshots now, can you add them again?

**Comment by hp6393** [comment]
This is especially true for standalone notes, because they have no parent item or title.
-------- Original message --------From: Emiliano Heyns <notifications@github.com> Date: 9/7/19  1:14 PM  (GMT-06:00) To: retorquere/zotero-report-customizer <zotero-report-customizer@noreply.github.com> Cc: hp6393 <harold.peach@gmail.com>, Author <author@noreply.github.com> Subject: Re: [retorquere/zotero-report-customizer] Select Item link in list of available report fields (#35) I saw a notification of a reply of yours, but I don't see the reply here. What did it say?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/retorquere/zotero-report-customizer/issues/35?email_source=notifications\u0026email_token=ANDVXZFUVCGUGT7XFHCRPJ3QIPVPXA5CNFSM4IUOMPXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6E63DQ#issuecomment-529132942",
"url": "https://github.com/retorquere/zotero-report-customizer/issues/35?email_source=notifications\u0026email_token=ANDVXZFUVCGUGT7XFHCRPJ3QIPVPXA5CNFSM4IUOMPXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6E63DQ#issuecomment-529132942",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hp6393** [comment]
Sure. I have them on my PC at home. I will be back there in about an hour and will send them to you through email.
-------- Original message --------From: Emiliano Heyns <notifications@github.com> Date: 9/7/19  2:53 PM  (GMT-06:00) To: retorquere/zotero-report-customizer <zotero-report-customizer@noreply.github.com> Cc: hp6393 <harold.peach@gmail.com>, Author <author@noreply.github.com> Subject: Re: [retorquere/zotero-report-customizer] Select Item link in list of available report fields (#35) I don't see those screenshots now, can you add them again?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/retorquere/zotero-report-customizer/issues/35?email_source=notifications\u0026email_token=ANDVXZBOSJB33M4C4B7JRMLQIQBC5A5CNFSM4IUOMPXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6FBB2Q#issuecomment-529141994",
"url": "https://github.com/retorquere/zotero-report-customizer/issues/35?email_source=notifications\u0026email_token=ANDVXZBOSJB33M4C4B7JRMLQIQBC5A5CNFSM4IUOMPXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6FBB2Q#issuecomment-529141994",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by retorquere** [comment]
Thanks. When responding by mail, can you clip out the message history? It's being pasted into the issue here and it makes it harder to read what's going on.

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.25.129](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.129.xpi) ("show select link for notes")

Install in Zotero by downloading [test build 5.0.25.129](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.129.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
.129 adds note links

**Comment by hp6393** [comment]
Yes, this fixed the standalone notes, but not the child notes. See attached.


[image: Child Note only.jpg]

I've also attached a Zotero RDF of the test entries I used.

**Comment by retorquere** [comment]
Attachments and images don't come through when responding by email, those can only be attached on github itself.

**Comment by hp6393** [comment]
I just edited the comment to include them here.

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.25.130](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.130.xpi) ("select links for child notes")

Install in Zotero by downloading [test build 5.0.25.130](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.25.130.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by hp6393** [comment]
5.0.25.130 addresses all three select link conditions. Thanks for you help with this!
