### ISSUE TITLE
Allow `$...$` as inline math delimiters

### ISSUE THREAD

**Issue by macchonchradha** [retorquere/zotero-report-customizer#36]
Using the hidden preference `extensions.zotero.report-customizer.MathJax` I have tried to add `$...$` as an inline math delimiter as indicated in <https://docs.mathjax.org/en/latest/options/input/tex.html?the-configuration-block> but I get "Error generating report". The JSON I have used (with and without line breaks is

```
{
  tex: {
    inlineMath: [
      ['$','$'],
      ['\\(','\\)']
    ],
    displayMath: [
      ['$$', '$$'],
      ['\\[', '\\]']
    ],
    processEscapes: true
  }
}
```
However, anything besides `{}` in the preference seems to cause "Error generating report". Version used is 5.0.29.

**Comment by retorquere** [comment]
That's not JSON; the JSON equivalent of what you have here would be

```
{     
  "tex": {
    "inlineMath": [
      [ "$", "$" ],
      [ "\\(", "\\)" ]
    ],  
    "displayMath": [
      [ "$$", "$$" ],
      [ "\\[", "\\]" ]
    ],
    "processEscapes": true
  }
}
```

**Comment by macchonchradha** [comment]
Thank you for your help. I'm obviously not good with JSON and was following the MathJax documentation. The JSON you provided does not produce an error but `$...$` still does not work for inline math. Is there a fix available?

**Comment by retorquere** [comment]
I've made it so you can use both the JS or JSON form now.  It also looks like https://docs.mathjax.org/en/latest/options/input/tex.html?the-configuration-block has an error, because https://docs.mathjax.org/en/v2.7-latest/configuration.html for example says that `tex:` should be `tex2jax:` and that does work for me.

**Comment by macchonchradha** [comment]
Thank you once again. I can confirm that `{"tex2jax":{"inlineMath":[["$","$"],["\\(","\\)"]],"displayMath":[["$$","$$"],["\\[","\\]"]],"processEscapes":true}}` in `extensions.zotero.report-customizer.MathJax` allows me to use `$...$` for inline math.

**Comment by retorquere** [comment]
Super, thanks for the conformation
