### ISSUE TITLE
"Backend not available" (port is different for Juris-M and Zotero)

### ISSUE THREAD

**Issue by dchawisher** [retorquere/zotero-report-customizer#37]
When I attempt to save my changes to the report, I get an error: "backend not available." If it matters, I'm using Juris-M, which ordinarily has no trouble with Zotero extensions.

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.31.143](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.31.143.xpi) ("port differs between zotero and jurism")

Install in Zotero by downloading [test build 5.0.31.143](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.31.143.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try the build linked above

**Comment by dchawisher** [comment]
It works! Phenomenal. Thank you so much.

**Comment by retorquere** [comment]
I've cut a new release, you'll be upgraded automatically.

**Comment by Roi03** [comment]
I have this issue, could I ask for the test build please? Where can I support the creator?

**Comment by retorquere** [comment]
Can you open a new issue? The "backend not available" is a generic error message, the actual cause was fixed in #37 and can't reasonably be happening to you now; if we continue the discussion here, dchawisher will be copied in on all our chatter without benefit to him/her.
