### ISSUE TITLE
Conflict with Better Bibtex?

### ISSUE THREAD

**Issue by nhan000** [retorquere/zotero-report-customizer#89]
I'm using Zotero 6.0.36, portable version, Windows 11.

Report Customizer only works when Better Bibtex is disabled. It showed a blank window when clicking "Generate Report from Item".

I've tried Better Bibtex versions from v6.7.177 to v6.7.155 and they didn't work. 

However, Report Customizer works as expected with Better Bibtex v6.7.114.

**Comment by retorquere** [comment]
I'll look into it in the coming week.

**Comment by nhan000** [comment]
Looks like only I have this problem that I've dealt with by install the older BBT version. Zotero 7 is officially out now so no need to look into this issue.
